name: durjog_sathi
description: A new Flutter project.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_analytics: ^11.5.0

flutter:
  uses-material-design: true
