name: durjog_sathi
description: A new Flutter project.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^3.14.0
  firebase_auth: ^5.5.1
  firebase_analytics: ^11.5.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.14.4
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^5.6.9
  http: ^1.2.1
  flutter_polyline_points: ^2.0.0
  webview_flutter: ^4.2.2
  carousel_slider: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"