name: durjog_sathi
description: A new Flutter project.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_analytics: ^11.5.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/