// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrgaNKF4S5PtDLV8upcGf91tD8fEch5Fk',
    appId: '1:488200792732:web:3b1c67b8c1a9f8c4afdb59',
    messagingSenderId: '488200792732',
    projectId: 'durjog-bondhu-463319',
    authDomain: 'durjog-bondhu-463319.firebaseapp.com',
    storageBucket: 'durjog-bondhu-463319.firebasestorage.app',
    measurementId: 'G-JZGR478CDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvH2rD-cGZNRHz8yDrUEHGHwJ-D1lIfPA',
    appId: '1:488200792732:android:92cfdc94be708035afdb59',
    messagingSenderId: '488200792732',
    projectId: 'durjog-bondhu-463319',
    storageBucket: 'durjog-bondhu-463319.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrgaNKF4S5PtDLV8upcGf91tD8fEch5Fk',
    appId: '1:488200792732:web:52ee62423ed636b9afdb59',
    messagingSenderId: '488200792732',
    projectId: 'durjog-bondhu-463319',
    authDomain: 'durjog-bondhu-463319.firebaseapp.com',
    storageBucket: 'durjog-bondhu-463319.firebasestorage.app',
    measurementId: 'G-BWMFW48XTT',
  );
}
